game: "Kingdom Come: Deliverance"
api: 1
steamID: 379430
uid: com.thegreatcabbage.kcd
author: TheGreatCabbage
packageName: "kcd"
features:
  - graphics
  - keymaps
  - saves

graphicsConfig: C:\Users\$!USERNAME!$\Saved Games\kingdomcome\profiles\default\attributes.xml
keymapConfig: C:\Users\$!USERNAME!$\Saved Games\kingdomcome\profiles\default\actionmaps.xml
saves: C:\Users\$!USERNAME!$\Saved Games\kingdomcome\saves

gameDirectory: "KingdomComeDeliverance"
verificationPaths:
  - Bin/Win64/KingdomCome.exe
