game: "Kingdom Come: Deliverance"
api: 1
steamID: 379430
uid: com.thegreatcabbage.kcd
author: TheGreatCabbage
packageName: "kcd"
features:
  - graphics
  
graphicsConfig: TODO

gameDirectory: "KingdomComeDeliverance"
verificationPaths:
  - Bin/Win64/KingdomCome.exe
